#!/usr/bin/echo "myprofile must be *sourced* by bash sessions/scripts!"
# -*- shell-script -*-

myprofile() {
  local _default _dir _script _src _verbose
  local -a _scripts _search

  while [ $# -gt 0 ] ; do
    case "$1" in
         -h|--help) echo "Usage: $FUNCNAME [--help | --install | [--verbose] [{script}]]";
                    return 0;;
      -i|--install) if [[ "$(id -u)" == "0" ]] ; then
                      ln -sfv "$MYPROFILE" "/etc/profile.d/zz-$FUNCNAME.sh"
                    else
                      touch ~/.bash_profile
                      _script="$(sed "\~$MYPROFILE~d" ~/.bash_profile)"
                      echo -e "source $MYPROFILE\n\n$_script" >~/.bash_profile
                      grep --with-filename "$MYPROFILE" ~/.bash_profile
                    fi
                    return 0;;
      -v|--verbose) _verbose=echo;;
                -*) echo "$FUNCNAME: Unsupported option: $1" >&2;
                    return 1;;
                 *) _scripts+=("$1");;
    esac
    shift
  done
#set -x 
  _search=("$HOME/.config/$FUNCNAME" "/etc/$FUNCNAME" "${MYPROFILE%/*}")

  if [[ ${#_scripts[@]} -eq 0 && -n "$PS1" ]] ; then
    for _dir in ${_search[@]} ; do
      _default="$_dir/default"
      if [ -s "$_default" ] ; then
        _scripts=($(grep -v -E "^[[:space:]]*[#_]" "$_default"))
        break
      fi
    done
  fi

  for _script in ${_scripts[@]} ; do

    if [ -s "$_script" ] ; then
      _src="$_script"
    else
      for _dir in ${_search[@]} ; do
        _src="$_dir/$_script"
        [ -s "$_src" ] && break
      done
    fi

    if [ ! -s "$_src" ] ; then
      echo "Missing myprofile script \"$_script\"!" >&2
      return 1
    fi

    [ -z "$_verbose" ] || echo "Source \"$_src\"."

    if ! source "$_src" ; then
      echo "Load of myprofile script \"$_src\" has failed!" >&2
      return 1
    fi

  done
}
export -f myprofile

# CAUTION: During initial "source .../myprofile" it is assured that "$BASH_SOURCE[0]" points to this
# script. For later myprofile() calls this is not guaranteed.
export MYPROFILE="$(realpath "${BASH_SOURCE[0]}")"

myprofile "$@"
